config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :contacts
  resources :messages
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
end

app/models/message.rb
class Message < ActiveRecord::Base

  define_method :index do
    binding.pry
  end

  define_method :new do
    binding.pry
  end
  define_method :create do
    binding.pry
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :presence => true
  validates :email, :presence => true
  validates :password, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  define_method :index do
    binding.pry
  end

  define_method :show do
    if params[:id] == 'contact'
      @contact = Contact.new
      render :contact
    end
  end

  define_method :create do

  end

  private
  define_method :contacts_params do

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  define_method :new do
    @message = Message.new
    redirect :dashboard
  end
end

app/controllers/users_controller.rb
require './lib/assets/modbotmain'

class UsersController < ApplicationController

  define_method :index do
    render :index
  end

  define_method :show do
    if params[:id] == "about"
      render :about
    elsif params[:id] == "support"
      render :support
    elsif params[:id]. == "dashboard"
      Thread.new do
        ModBotMain.new self
      end
      @message = "Welcome!"
      render :dashboard
    elsif params[:id] == "login"
      @user = User.new
      render :login
    end
  end

  define_method :new do
    @user = User.new
    render :new
  end

  define_method :create do
    if params[:user][:name].class == NilClass
      @users = User.all
      @users. each do |u|
        if u.email == params[:user][:email]
          if u.password == params[:user][:password]
            @message = "Welcome!"
            redirect_to user_path( "dashboard" )
            return
          end
        end
      end
      @user = User.new
      render :new
    else
      @user = User.new user_params
      if @user.save
        redirect_to users_path
      else
        render :new
      end
    end
  end

  define_method :read do |message|
    puts "CONTROLLER:" + message
    @message = Message.new
    @message.from = "test"
    @message.message = message
    puts "NEW MESSAGE " + @message.message
    message_path( @message )
  end

private
  define_method :user_params do
    params.require( :user ).permit( :name, :email, :password )
  end

  define_method :user_login_params do
    params.require( :user ).permit( :email, :password )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/contact.html.erb
<div class="col-xs-12">
  <div class="col-xs-4 col-xs-offset-1">
    <h3 class="headers">Contact</h3>
  </div>
</div>

<div class="col-xs-2 col-xs-offset-5">
  <%= render "contacts_layouts/contacts_submitform" %>
</div>

app/views/contacts_layouts/_contacts_submitform.html.erb
<%= form_for @contact do |c| %>
    <h4><%= c.label :name, class: "label label-default" %> </h4>
    <%= c.text_field :name, class: "contacttextfield" %>
    <h4><%= c.label :email, class: "label label-default" %> </h4>
    <%= c.text_field :email, class: "contacttextfield" %>
    <h4><%= c.label :topic, class: "label label-default" %> </h4>
    <%= c.select( :topic, [['Help','Help'],['Question','Question'],['Comment','Comment'],['Other', 'Other']], {}, { :class => "contactselect" } ) %>
    <h4><%= c.label :info, class: "label label-default" %> </h4>
    <%= c.text_area :info, class: "contacttextarea"  %> <br \>
    <%= c.submit  "Submit", class: "btn btn-primary" %>
<%end%>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div class="errorbox">
      <h3 style="display: inline;">Please fix these errors:</h3><a href="#" class="closebutton"></a>
      <ul class="errors">
        <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Broadcaster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Transmit", users_path, class: "navbar-brand brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "About", user_path( "about" )%></li>
            <li><%= link_to "Contact", contact_path( "contact" )%></li>
            <li><%= link_to "Support", user_path( "support" )%></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Login", user_path( "login" ) %></li>
            <li><%= button_to "Sign Up", new_user_url, class: "btn btn-primary", :method => :get %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
</div>

<%= yield %>


</body>
<div class="col-xs-12">
  <hr>
  <footer style="text-align:center;">Copywrite Kyle Langley <2016></footer>
</div>
</html>

app/views/users/about.html.erb
<div class="col-xs-4 col-xs-offset-1">
  <%= render "users_layouts/users_about" %>
</div>

app/views/users/contact.html.erb
<div class="col-xs-4 col-xs-offset-4">
  <%= render "users_layouts/users_contactform" %>
</div>

app/views/users/dashboard.html.erb
<%= render "users_layouts/users_dashboard", :object => @message %>

<%= puts "DASHBOARD: " + @message %>

app/views/users/login.html.erb
<div class="col-xs-12">
  <div class="row">
    <div class="col-xs-4 col-xs-offset-1" style="margin-bottom:42px;">
      <h3 class="headers">Login</h3>
    </div>
  </div>
  <div class="col-xs-2 col-xs-offset-5">
    <%= render "users_layouts/users_loginform", :object => @user %>
  </div>
</div>

app/views/users/new.html.erb
<div class="col-xs-12">
  <div class="col-xs-4 col-xs-offset-1">
    <h3 class="headers">Sign up</h3>
  </div>
</div>

<div class="col-xs-2 col-xs-offset-5">
  <%= render "users_layouts/users_newaccountform" %>
</div>

app/views/users/support.html.erb
<div class="col-xs-12">
  <div class="col-xs-4 col-xs-offset-1">
    <h3 class="headers">Support</h3>
  </div>
</div>

<div class="col-xs-4 col-xs-offset-2">
  <a href="#signup" class="index">Signing up</a> <br \>
  <a href="#modbot" class="index">Moderation Bot</a> <br \>
  <a href="#broadview" class="index">Broadcasting View</a> <br \>
  <a href="#alerts" class="index">Alerts</a> <br \>
</div>

<a href="" class="back-to-top"><span class="glyphicon glyphicon glyphicon-circle-arrow-up"></span></a>

<div id="signup" class="col-xs-6 col-xs-offset-3">
  <%= render "users_help_layouts/users_signuphelp" %>
</div>

<div id="modbot" class="col-xs-6 col-xs-offset-3">
  <%= render "users_help_layouts/users_modbothelp" %>
</div>

<div id="broadview" class="col-xs-6 col-xs-offset-3">
  <%= render "users_help_layouts/users_alertviewhelp" %>
</div>

<div id="alerts" class="col-xs-6 col-xs-offset-3">
  <%= render "users_help_layouts/users_alertshelp" %>
</div>

app/views/users_help_layouts/_users_dashboardhelp.html.erb
<div class="col-xs-4 col-xs-offset-1" style="margin-bottom:42px;">
  <h3 class="headers">Dashboard</h3>
</div>

<div class="row" style="margin:42px;">
  <div class="col-xs-12">
    <div class="col-xs-1 col-xs-offset-1">
      <%= render "users_layouts/users_dashboardcontrol" %>
    </div>

    <div class="col-xs-3">
      <h3>Chat</h3>
      <%= render "users_layouts/users_chatwindow" %>
    </div>

    <div class="col-xs-6">
      <h3>Current Broadcast View <a href="" class="index" style="font-size:14px !important">Edit</a></h3>
      <%= render "users_layouts/users_alertview" %>
    </div>
  </div>
</div>

app/views/users_layouts/_users_about.html.erb
<h3 class="headers">About</h3>

app/views/users_layouts/_users_alertview.html.erb
<div id="example-one" contenteditable="true">
  <style scoped>
    #example-one { margin-bottom: 10px; }
    [contenteditable="true"] { padding: 10px; background-color: greenyellow; height: 512px; }
  </style>
</div>

<div class="col-xs-1 col-xs-offset-11"><a href="" class="index">Popout</a></div>

app/views/users_layouts/_users_chatwindow.html.erb
<div id="chatwindow" class="chatwindow"><%= @message %></div>

app/views/users_layouts/_users_contactform.html.erb
<h3>Contact</h3>

app/views/users_layouts/_users_dashboard.html.erb
<div class="col-xs-4 col-xs-offset-1" style="margin-bottom:42px;">
  <h3 class="headers">Dashboard</h3>
</div>

<div class="row" style="margin:42px;">
  <div class="col-xs-12">
    <div class="col-xs-1 col-xs-offset-1">
      <%= render "users_layouts/users_dashboardcontrol" %>
    </div>

    <div class="col-xs-3">
      <h3>Chat</h3>
      <%= render "users_layouts/users_chatwindow", :object => @message %>
    </div>

    <div class="col-xs-6">
      <h3>Current Broadcast View <a href="" class="index" style="font-size:14px !important">Edit</a></h3>
      <%= render "users_layouts/users_alertview" %>
    </div>
  </div>
</div>

app/views/users_layouts/_users_dashboardcontrol.html.erb
<a href="" class="index">Account</a> <br \>
<a href="" class="index">Moderation Settings</a> <br \>
<a href="" class="index">Alert View Files</a> <br \>

app/views/users_layouts/_users_loginform.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user do |f| %>
  <h4><%= f.label :email, class: "label label-default" %></h4>
  <%= f.email_field :email, class: "contacttextfield" %>
  <h4><%= f.label :password, class: "label label-default" %></h4>
  <%= f.password_field :password, class: "contacttextfield" %><br \>
  <%= f.submit  "Submit", class: "btn btn-primary" %>
<%end%>

app/views/users_layouts/_users_newaccountform.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user do |c| %>
    <h4><%= c.label :name, class: "label label-default" %> </h4>
    <%= c.text_field :name, class: "contacttextfield" %>
    <h4><%= c.label :email, class: "label label-default" %> </h4>
    <%= c.text_field :email, class: "contacttextfield" %>
    <h4><%= c.label :password, class: "label label-default" %> </h4>
    <%= c.password_field :password, class: "contacttextfield" %> <br \>
    <%= c.submit  "Create", class: "btn btn-primary" %>
<%end%>